config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :accounts
  resources :ticket_types
  resources :products
  resources :statuses
  
  get 'static_pages/admin'

  get 'home' => 'static_pages#home'

  get 'about' => 'static_pages#about'
  
  get 'contact' => 'static_pages#contact_us'
  
  get 'signup' => 'accounts#new'
  
  get 'ticket' => 'tickets#new'
  
  get 'login'=> 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  

  
  

  root 'sessions#new'

 
end

app/controllers/ticket_types_controller.rb
class TicketTypesController < ApplicationController
  before_action :set_ticket_type, only: [:show, :edit, :update, :destroy]

  # GET /ticket_types
  # GET /ticket_types.json
  def index
    @ticket_types = TicketType.all
  end

  # GET /ticket_types/1
  # GET /ticket_types/1.json
  def show
  end

  # GET /ticket_types/new
  def new
    @ticket_type = TicketType.new
  end

  # GET /ticket_types/1/edit
  def edit
  end

  # POST /ticket_types
  # POST /ticket_types.json
  def create
    @ticket_type = TicketType.new(ticket_type_params)

    respond_to do |format|
      if @ticket_type.save
        format.html { redirect_to @ticket_type, notice: 'Ticket type was successfully created.' }
        format.json { render :show, status: :created, location: @ticket_type }
      else
        format.html { render :new }
        format.json { render json: @ticket_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticket_types/1
  # PATCH/PUT /ticket_types/1.json
  def update
    respond_to do |format|
      if @ticket_type.update(ticket_type_params)
        format.html { redirect_to @ticket_type, notice: 'Ticket type was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket_type }
      else
        format.html { render :edit }
        format.json { render json: @ticket_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_types/1
  # DELETE /ticket_types/1.json
  def destroy
    @ticket_type.destroy
    respond_to do |format|
      format.html { redirect_to ticket_types_url, notice: 'Ticket type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket_type
      @ticket_type = TicketType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_type_params
      params.require(:ticket_type).permit(:type)
    end
end

app/helpers/ticket_types_helper.rb
module TicketTypesHelper
end

app/views/ticket_types/_form.html.erb
<%= form_for(@ticket_type) do |f| %>
  <% if @ticket_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket_type.errors.count, "error") %> prohibited this ticket_type from being saved:</h2>

      <ul>
      <% @ticket_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ticket_types/edit.html.erb
<h1>Editing Ticket Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket_type %> |
<%= link_to 'Back', ticket_types_path %>

app/views/ticket_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ticket Types</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ticket_types.each do |ticket_type| %>
      <tr>
        <td><%= ticket_type.type %></td>
        <td><%= link_to 'Show', ticket_type %></td>
        <td><%= link_to 'Edit', edit_ticket_type_path(ticket_type) %></td>
        <td><%= link_to 'Destroy', ticket_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket type', new_ticket_type_path %>

app/views/ticket_types/new.html.erb
<h1>New Ticket Type</h1>

<%= render 'form' %>

<%= link_to 'Back', ticket_types_path %>

app/views/ticket_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @ticket_type.type %>
</p>

<%= link_to 'Edit', edit_ticket_type_path(@ticket_type) %> |
<%= link_to 'Back', ticket_types_path %>