config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :accounts
  resources :ticket_types
  resources :products
  resources :statuses
  
  get 'static_pages/admin'

  get 'home' => 'static_pages#home'

  get 'about' => 'static_pages#about'
  
  get 'contact' => 'static_pages#contact_us'
  
  get 'signup' => 'accounts#new'
  
  get 'ticket' => 'tickets#new'
  
  get 'login'=> 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  

  
  

  root 'sessions#new'

 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BBW Supportdesk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand">BBW SupportDesk</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          
          <ul class="nav navbar-nav navbar-right">
            
            <% if logged_in? %>
                <% if current_user.admin? %>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Admin <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                <li><%= link_to "Display Tickets", tickets_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Accounts Maint", accounts_path %></li>
                <li><%= link_to "Product Maint", products_path %></li>
                </ul>
                <% end %>
            <li><%= link_to "Home", home_path %></li>
            <li><%= link_to "Create Ticket", new_ticket_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Account Info", current_user %></li>
                <li><%= link_to "Edit Account", edit_account_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Logout", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
            <li><%= link_to "Logout", logout_path, method: "delete" %></li>
            <% else %>
            <li><%= link_to "Login", login_path %></li>
            <li><%= link_to "Create Account", signup_path %></li>
            <% end %>
            <li><%= link_to "Contact", contact_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
<%= yield %>

</body>

</html>